### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by sfahadshahzad** [dkashin/pipencoder-base#1]
Hi,

Hope you are doing well,

Would like to appreciate you for the wonderful peace of work.
Can you please guide me how to install this with decklink video input preset.

Regards,

Fahad

**Comment by josephril** [comment]
Hello Kashin,

I had tried installing pipencoder-base for some reason unable to setup pipencoder web server 
using Flask nginx uWSGI  for some reason cannot start the api server properly 

I would request you if you can share me some tips for installation of pipencoder or a bash script if possible 

would appreciate your help 

Best regards 


Joseph 




**some error listed below tried to fix some of them but seems need to change setup approach** 

Error compiling Cython file:
------------------------------------------------------------
...
                  self.logger.info('[PresetsManager] Update: Associated active jobs were restated ' + str(active_job_counter))
              info = _JSONTools.JSONToString(json_data = preset_data)
              _AlarmManager.OnAction(report = { 'event': 'AV Preset ' + action, 'info': info[:-2] })
              self.logger.info('[PresetsManager] ' + action + ': OK')
              return response, 200, 'OK'
            except FileNotFoundError:
                                   ^
------------------------------------------------------------

main/preset/preset.py:115:36: undeclared name not builtin: FileNotFoundError

Error compiling Cython file:
------------------------------------------------------------
...
                  self.logger.info('[PresetsManager] Update: Associated active jobs were restated ' + str(active_job_counter))
              info = _JSONTools.JSONToString(json_data = preset_data)
              _AlarmManager.OnAction(report = { 'event': 'AV Preset ' + action, 'info': info[:-2] })
              self.logger.info('[PresetsManager] ' + action + ': OK')
              return response, 200, 'OK'
            except FileNotFoundError:
                                   ^
------------------------------------------------------------

main/preset/preset.py:115:36: undeclared name not builtin: FileNotFoundError
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 1167, in cythonize_one_helper
    return cythonize_one(*m)
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 1149, in cythonize_one
    raise CompileError(None, pyx_file)
CompileError: main/preset/preset.py
[ 65/101] Cythonizing main/server/__init__.py
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 1167, in cythonize_one_helper
    return cythonize_one(*m)
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 1149, in cythonize_one
    raise CompileError(None, pyx_file)
CompileError: main/preset/preset.py
[ 66/101] Cythonizing main/server/__init__.py
[ 67/101] Cythonizing main/server/server.py
[ 68/101] Cythonizing main/server/server.py
[ 69/101] Cythonizing main/server/views.py
Traceback (most recent call last):
  File "make_bin.py", line 47, in <module>
    'always_allow_keywords': True
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 1018, in cythonize
    result.get(99999)  # seconds
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get
[ 70/101] Cythonizing main/server/views.py
    raise self._value
Cython.Compiler.Errors.CompileError: main/preset/preset.py
